### ISSUE TITLE
Bump version to 0.1.0

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-key#5]
This way anything that depends on this will get bug fixes.

Also, update the repos that depend on this to use `^0.1.0` and publish patch releases of those:
```
$ npm ls can-stache-key
can@3.9.0 /Users/kevin/dev/canjs
├─┬ can-component@3.3.0
│ └── can-stache-key@0.0.2
├─┬ can-compute@3.3.1
│ └── can-stache-key@0.0.2
├─┬ can-connect@1.5.5
│ └─┬ can-stache@3.3.3
│   └── can-stache-key@0.0.2
├─┬ can-control@3.2.0
│ └── can-stache-key@0.0.2
├─┬ can-ejs@3.1.2
│ └── can-stache-key@0.0.3
├─┬ can-map@3.3.1
│ └── can-stache-key@0.0.2
├─┬ can-stache@3.2.0
│ └── can-stache-key@0.0.2
├─┬ can-stache-bindings@3.4.4
│ └── can-stache-key@0.0.2
├── can-stache-key@0.0.4
└─┬ can-view-scope@3.3.2
  └── can-stache-key@0.0.3
```

**Comment by bgando** [comment]
Open PRs (all failing builds because can-stache-key 0.1.0 isn't released yet):
https://github.com/canjs/can-view-scope/pull/85
https://github.com/canjs/can-stache-bindings/pull/274
https://github.com/canjs/can-stache/pull/270
https://github.com/canjs/can-map/pull/62
https://github.com/canjs/can-ejs/pull/39
https://github.com/canjs/can-control/pull/88
https://github.com/canjs/can-compute/pull/100
https://github.com/canjs/can-component/pull/141

Not included:
- can-connect (master branch doesn't have the dependency)
- can-stache-key (because this will need to be done w/ npm scripts)
